FROM maven:3.8.6-openjdk-11-slim AS build

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package

FROM openjdk:11-jre-slim

WORKDIR /app
COPY --from=build /app/target/common-1.0-SNAPSHOT.jar ./common.jar

CMD ["java", "-jar", "common.jar"]
